# Generated by Django 2.1.15 on 2020-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='report', max_length=100)),
                ('file', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
