# Generated by Django 3.1.2 on 2020-10-07 02:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CT_QC_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Oct-06-2020', max_length=100)),
                ('daily_qc', jsonfield.fields.JSONField()),
                ('monthly_qc', jsonfield.fields.JSONField()),
            ],
        ),
    ]
