# Generated by Django 3.1.2 on 2020-10-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ct_qc_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct_qc_report',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ct_qc_report',
            name='name',
            field=models.CharField(default='Oct-07-2020', max_length=100),
        ),
    ]
